FROM mysql:latest

WORKDIR ./docker-entrypoint-initdb.d

COPY ./data.sql ./docker-entrypoint-initdb.d/data.sql

ENV MYSQL_DATABASE=usersdb
ENV MYSQL_USER=test
ENV MYSQL_PASSWORD=1234
ENV MYSQL_ROOT_PASSWORD=1234

EXPOSE 3306